# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12model_server.proto\x12\nimg_server\"\x97\x01\n\x08Metadata\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0c\n\x04seed\x18\x04 \x01(\x05\x12\x12\n\niterations\x18\x05 \x01(\x05\x12\x10\n\x08strength\x18\x06 \x01(\x02\x12\x16\n\x0eguidance_scale\x18\x07 \x01(\x02\x12\x10\n\x08priority\x18\x08 \x01(\x02\"@\n\x07Request\x12&\n\x08metadata\x18\x01 \x01(\x0b\x32\x14.img_server.Metadata\x12\r\n\x05image\x18\x02 \x01(\x0c\"\x19\n\x08Response\x12\r\n\x05image\x18\x03 \x01(\x0c\x32K\n\x0cImGenService\x12;\n\x0egenerate_image\x12\x13.img_server.Request\x1a\x14.img_server.Responseb\x06proto3')



_METADATA = DESCRIPTOR.message_types_by_name['Metadata']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Metadata = _reflection.GeneratedProtocolMessageType('Metadata', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'model_server_pb2'
  # @@protoc_insertion_point(class_scope:img_server.Metadata)
  })
_sym_db.RegisterMessage(Metadata)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'model_server_pb2'
  # @@protoc_insertion_point(class_scope:img_server.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'model_server_pb2'
  # @@protoc_insertion_point(class_scope:img_server.Response)
  })
_sym_db.RegisterMessage(Response)

_IMGENSERVICE = DESCRIPTOR.services_by_name['ImGenService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METADATA._serialized_start=35
  _METADATA._serialized_end=186
  _REQUEST._serialized_start=188
  _REQUEST._serialized_end=252
  _RESPONSE._serialized_start=254
  _RESPONSE._serialized_end=279
  _IMGENSERVICE._serialized_start=281
  _IMGENSERVICE._serialized_end=356
# @@protoc_insertion_point(module_scope)
