"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import model_server_pb2

class ImGenServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    generate_image: grpc.UnaryUnaryMultiCallable[
        model_server_pb2.ImGenRequest,
        model_server_pb2.ImGenResponse,
    ]
    tokenize_prompt: grpc.UnaryUnaryMultiCallable[
        model_server_pb2.TokenizeRequest,
        model_server_pb2.TokenizeResponse,
    ]

class ImGenServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def generate_image(
        self,
        request: model_server_pb2.ImGenRequest,
        context: grpc.ServicerContext,
    ) -> model_server_pb2.ImGenResponse: ...
    @abc.abstractmethod
    def tokenize_prompt(
        self,
        request: model_server_pb2.TokenizeRequest,
        context: grpc.ServicerContext,
    ) -> model_server_pb2.TokenizeResponse: ...

def add_ImGenServiceServicer_to_server(servicer: ImGenServiceServicer, server: grpc.Server) -> None: ...
