"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Image(google.protobuf.message.Message):
    """TODO: tokenized prompt input; CLIP embedding input; prompt weighting"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    width: builtins.int
    height: builtins.int
    dtype: builtins.str
    data: builtins.bytes
    def __init__(
        self,
        *,
        width: builtins.int = ...,
        height: builtins.int = ...,
        dtype: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "dtype", b"dtype", "height", b"height", "width", b"width"]) -> None: ...

global___Image = Image

class ImGenRequestMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    SEED_FIELD_NUMBER: builtins.int
    ITERATIONS_FIELD_NUMBER: builtins.int
    STRENGTH_FIELD_NUMBER: builtins.int
    GUIDANCE_SCALE_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    TEST_NO_COMPUTE_FIELD_NUMBER: builtins.int
    prompt: builtins.str
    width: builtins.int
    height: builtins.int
    seed: builtins.int
    iterations: builtins.int
    strength: builtins.float
    guidance_scale: builtins.float
    priority: builtins.int
    """request priority. Higher number -> execute sooner."""
    test_no_compute: builtins.bool
    """set to true to skip the expensive parts (for testing)"""
    def __init__(
        self,
        *,
        prompt: builtins.str = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        seed: builtins.int = ...,
        iterations: builtins.int = ...,
        strength: builtins.float = ...,
        guidance_scale: builtins.float = ...,
        priority: builtins.int = ...,
        test_no_compute: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["guidance_scale", b"guidance_scale", "height", b"height", "iterations", b"iterations", "priority", b"priority", "prompt", b"prompt", "seed", b"seed", "strength", b"strength", "test_no_compute", b"test_no_compute", "width", b"width"]) -> None: ...

global___ImGenRequestMetadata = ImGenRequestMetadata

class ImGenResponseMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_RECEIVED_TIME_FIELD_NUMBER: builtins.int
    START_PROCESSING_TIME_FIELD_NUMBER: builtins.int
    FINISH_PROCESSING_TIME_FIELD_NUMBER: builtins.int
    PROMPT_TOKENS_FIELD_NUMBER: builtins.int
    QUEUE_SIZE_FIELD_NUMBER: builtins.int
    @property
    def request_received_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def start_processing_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def finish_processing_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def prompt_tokens(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Can be used to detect if the prompt was cut"""
    queue_size: builtins.int
    """Worker queue size just before enqueueing"""
    def __init__(
        self,
        *,
        request_received_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        start_processing_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        finish_processing_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        prompt_tokens: collections.abc.Iterable[builtins.str] | None = ...,
        queue_size: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["finish_processing_time", b"finish_processing_time", "request_received_time", b"request_received_time", "start_processing_time", b"start_processing_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["finish_processing_time", b"finish_processing_time", "prompt_tokens", b"prompt_tokens", "queue_size", b"queue_size", "request_received_time", b"request_received_time", "start_processing_time", b"start_processing_time"]) -> None: ...

global___ImGenResponseMetadata = ImGenResponseMetadata

class ImGenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQ_METADATA_FIELD_NUMBER: builtins.int
    IMAGE_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    @property
    def req_metadata(self) -> global___ImGenRequestMetadata: ...
    @property
    def image(self) -> global___Image: ...
    dtype: builtins.str
    def __init__(
        self,
        *,
        req_metadata: global___ImGenRequestMetadata | None = ...,
        image: global___Image | None = ...,
        dtype: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["image", b"image", "req_metadata", b"req_metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dtype", b"dtype", "image", b"image", "req_metadata", b"req_metadata"]) -> None: ...

global___ImGenRequest = ImGenRequest

class ImGenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQ_METADATA_FIELD_NUMBER: builtins.int
    RESP_METADATA_FIELD_NUMBER: builtins.int
    IMAGE_FIELD_NUMBER: builtins.int
    @property
    def req_metadata(self) -> global___ImGenRequestMetadata: ...
    @property
    def resp_metadata(self) -> global___ImGenResponseMetadata: ...
    @property
    def image(self) -> global___Image: ...
    def __init__(
        self,
        *,
        req_metadata: global___ImGenRequestMetadata | None = ...,
        resp_metadata: global___ImGenResponseMetadata | None = ...,
        image: global___Image | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["image", b"image", "req_metadata", b"req_metadata", "resp_metadata", b"resp_metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["image", b"image", "req_metadata", b"req_metadata", "resp_metadata", b"resp_metadata"]) -> None: ...

global___ImGenResponse = ImGenResponse

class TokenizeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    prompt: builtins.str
    def __init__(
        self,
        *,
        prompt: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["prompt", b"prompt"]) -> None: ...

global___TokenizeRequest = TokenizeRequest

class TokenizeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_TOKENS_FIELD_NUMBER: builtins.int
    @property
    def prompt_tokens(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        prompt_tokens: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["prompt_tokens", b"prompt_tokens"]) -> None: ...

global___TokenizeResponse = TokenizeResponse
